fix json error
octokit/webhooks pull request #567
Opened 2021-09-28 21:14 UTC by ahl

2021-09-28 21:16 UTC, G-Rath commented
Could you provide some details about why you think we need to make this change? we test our schemas against a bunch of payload examples and they're passing fine as is using `ajv`.

2021-10-01 06:16 UTC, ahl commented
I count 17 places where there's either `"enum": [true]` or `"enum": [false]`:

```
$ git ls-files | grep schema.json | xargs -L1 jq -c '.. | select(.enum? == [true])'
{"type":"boolean","enum":[true]}
{"type":"boolean","enum":[true]}
{"type":"boolean","enum":[true]}
{"enum":[true]}
{"type":"boolean","enum":[true]}
{"type":"boolean","enum":[true],"description":"Indicates whether or not the pull request is a draft."}
{"type":"boolean","enum":[true],"description":"Whether the release is identified as a prerelease or a full release."}
{"type":"boolean","enum":[true],"description":"Whether the repository is archived.","default":false}
{"type":"boolean","enum":[true],"description":"Whether the repository is private or public."}
$ git ls-files | grep schema.json | xargs -L1 jq -c '.. | select(.enum? == [false])'
{"type":"boolean","enum":[false]}
{"type":"boolean","enum":[false]}
{"type":"boolean","enum":[false]}
{"type":"boolean","enum":[false]}
{"type":"boolean","enum":[false]}
{"type":"boolean","enum":[false],"description":"Indicates whether or not the pull request is a draft."}
{"type":"boolean","enum":[false],"description":"Whether the repository is private or public."}
{"type":"boolean","enum":[false],"description":"Whether the repository is archived.","default":false}
```

This is the only instance that omits the type.

This PR was to add consistency, but if that's not a goal feel free to close it.

2021-10-01 13:45 UTC, wolfy1339 commented
With that explanation I understand what you are trying to fix.

The `"type": "boolean"` should be in the same object as the `enum`, not in the parent object

2021-10-01 13:56 UTC, wolfy1339 requested changes

2021-10-01 13:56 UTC, wolfy1339 commented on payload-schemas/api.github.com/fork/event.schema.json
> +          "properties": { "type": "boolean", "fork": { "enum": [true] } },
```suggestion
          "properties": { "fork": { "type": "boolean",  "enum": [true] } },
```

2021-10-01 14:57 UTC, wolfy1339 approved these changes

2021-10-01 15:09 UTC, wolfy1339 commented
Can you lint the files?

2021-10-01 17:42 UTC, merged