feat: Add missing date-time format to time fields
octokit/webhooks pull request #655
Opened 2022-06-30 17:21 UTC by Helcaraxan

While doing some parsing & codegen work based on the JSON specs I realised that some time-based fields were missing the `date-time` format validation which is a very nice-to-have when dealing with unmarshalling into typed languages.

This PR's changes solely focus on adding those missing format hints.

2022-06-30 20:25 UTC, wolfy1339 requested changes
Just a little nitpick, can you have the `null` as the last value in the `oneOf`s

2022-07-01 13:24 UTC, Helcaraxan commented
Of course @wolfy1339. Sorry about that oversight. Should be fixed now.

2022-07-01 13:30 UTC, Helcaraxan commented
By the way should I rename the PR to get a `bug:` prefix for semver? I see that you applied the `Bug` label to this. I used the feature-level one as I was not sure how the project considers adding validation logic with respect to semver.

2022-07-01 18:52 UTC, wolfy1339 approved these changes

2022-07-01 18:53 UTC, gr2m commented
@wolfy1339 I don't think this changes anything for typescript though, other than https://github.com/octokit/webhooks/pull/655/files#diff-1680c176c64b33118d8088f64fbd82ff896d471c6d18e1d9911ef9aa695c7b0eL3429, right? I just ask because you added the `typescript` label? This pull request is just improving the JSON Schemas, which I agree is a feature, as it's an addition?

2022-07-01 18:55 UTC, wolfy1339 commented
>By the way should I rename the PR to get a `bug:` prefix for semver?

It's fine, we can change it if needed when we merge the PR

> I don't think this changes anything for typescript though, other than https://github.com/octokit/webhooks/pull/655/files#diff-1680c176c64b33118d8088f64fbd82ff896d471c6d18e1d9911ef9aa695c7b0eL3429, right?

That would be correct.

> I just ask because you added the `typescript` label?

I didn't label this PR, you did :laughing:

2022-07-01 18:56 UTC, Helcaraxan commented
Ah no, not me either, it was @gr2m. 😆 

I did just fix the linting issue. Apologies again, first time contributing to the project need to get the specifics right.

2022-07-01 18:59 UTC, wolfy1339 commented
> I did just fix the linting issue. Apologies again, first time contributing to the project need to get the specifics right.

No worries! You're doing just fine for a first time with this project

2022-07-01 19:02 UTC, merged

2022-07-01 19:03 UTC, Helcaraxan commented
Thank you both @wolfy1339 and @gr2m for getting this merged. 🙂